AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 
  Sample API using AWS API gateway and a lambda function

Resources:

  EndpointFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handler
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        Others:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        Base:
          Type: HttpApi
          Properties:
            Path: / 
            Method: ANY
      MemorySize: 128
      Timeout: 30